version: '3.3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: license-management
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    expose:
      - '3306'
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  app:
    build:
      context: .
      args:
        REACT_APP_API_ENDPOINT_URL: "http://localhost:8123"
    environment:
      QUARKUS_DATASOURCE_DB-KIND: mysql
      QUARKUS_DATASOURCE_USERNAME: user
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3306/license-management?serverTimezone=UTC
      QUARKUS_HTTP_PORT: 8080
    ports:
      - '8123:8080'